### PR TITLE
Added Hipchat notifications (similar to Slack)

### PR DESCRIPTION
**Pull request by jbrehm**
I just going to drop this here.

Really your build did what I needed, but I use Hipchat instead of Slack.

Also, the log line written every 5 seconds wasn't useful for us so I tuned that and if someone wants it on 'VERBOSE=1' will do the trick.

### CODE REVIEW

**Comment by egeland** [comment]
The version here seems to not be maintained. I have a fork with more information in the message, feel free to put this PR against that. 
I'm the creator of the helm chart and I hope to take over maintenance of this project. 😃

**Comment by mumoshu** [comment]
@jbrehm Thanks for your contribution 👍 LGTM.

@egeland Thanks for maintaining the fork! I've mentioned you in Twitter for discussion to either deprecate mine or move to an another shared place.

**Comment by egeland** [comment]
Might be a good idea to put it in a separate little group, where we can all contribute easily? 👍

**Comment by mumoshu** [comment]
@egeland Thanks for the response!
I've invited you to https://github.com/kube-aws/kube-spot-termination-notice-handler.
Once you've confirmed the invitation, you can of course push your fork to the new repo and fix inconsistency between this repository(if any).
Or I can do it if you are short on time right now.

**Comment by mumoshu** [comment]
Ah, sorry. You meant an dedicated github org. other than the kube-aws one?

**Comment by egeland** [comment]
No, that's perfect! I've accepted the invitation. Thanks!

**Pull request merged**
